name: USB/IP Base Image

on:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    # strategy:
    #   matrix:
    #     sdk: [0.16.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/usbip:latest
          # build-args: |
          #   ZEPHYR_SDK_VERSION=${{ matrix.sdk }}