name: Build USB/IP kernel module

on:
  workflow_dispatch:
    inputs:
      KERNEL_VERSION:
        required: true
        type: string
        default: v6.2

jobs:
  build:
    runs-on: ubuntu-latest

    container: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OS deps
        run: |
          apt update
          apt-get -y install --no-install-recommends \
          git \
          fakeroot \
          build-essential \
          ncurses-dev \
          xz-utils \
          libssl-dev \
          bc \
          flex \
          libelf-dev \
          bison \
          wget

      - name: Get source
        run: |
          wget https://github.com/torvalds/linux/archive/refs/tags/${{ inputs.KERNEL_VERSION }}.tar.gz
          tar xvf linux*

      # # Run IDs are unique per repo but are reused on re-runs
      # - name: Save artifact
      #   if: inputs.ARTIFACT == true
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build_artifacts_${{ github.run_id }}
      #     path: |
      #       build/zephyr/artifacts/*