name: Build USB/IP kernel module

on:
  workflow_dispatch:
    inputs:
      UBUNTU_CODENAME:
        required: true
        type: string
        default: jammy

jobs:
  build:
    runs-on: ubuntu-latest

    container: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-reqs for deps
        run: |
          echo 'deb-src http://archive.ubuntu.com/ubuntu jammy main' >> /etc/apt/sources.list
          echo 'deb-src http://archive.ubuntu.com/ubuntu jammy-updates main' >> /etc/apt/sources.list
          ln -fs /usr/share/zoneinfo/UTC /etc/localtime

      - name: OS deps
        run: |
          apt update
          apt-get -y install --no-install-recommends \
          ca-certificates \
          git \
          fakeroot \
          build-essential \
          ncurses-dev \
          xz-utils \
          libssl-dev \
          bc \
          flex \
          libelf-dev \
          bison \
          wget
          apt-get -y build-dep linux linux-image-generic

      - name: Get source
        run: |
          git clone --depth=1 git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/${{ inputs.UBUNTU_CODENAME }}

      - name: Build source
        run: |
          cd ${{ inputs.UBUNTU_CODENAME }}
          chmod a+x debian/scripts/*
          chmod a+x -R ./scripts
          make olddefconfig
          # make modules_prepare
          # make M=drivers/usb/usbip modules -j2
          make modules -j2
          ls drivers/usb

      # # Run IDs are unique per repo but are reused on re-runs
      # - name: Save artifact
      #   if: inputs.ARTIFACT == true
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build_artifacts_${{ github.run_id }}
      #     path: |
      #       build/zephyr/artifacts/*